# Dockerfile example 2.

# This Dockerfile will set up a minimal set of dependencies needed for running submissions.
# Note that tensorflow 1.15 or keras 2.3.1 are not included.
# Can be a useful starting point if solution needs, e.g. tensorflow 2.

FROM python:3.6

RUN pip3 install pandas numpy tqdm scikit-learn
