name: Package release

on:
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: alg/CATENets

jobs:
  deploy_linux:
    strategy:
      matrix:
        python-version:
          - cp36-cp36m

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set target Python version PATH
        run: |
            echo "/opt/python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/release_linux.sh
